server:
  port: 8020
spring:
  #???????
  application:
    name: rabbitmq-provider
  #??rabbitMq ???
  rabbitmq:
    host: 121.40.93.1
    port: 5672
    username: admin
    password: 123456
    #??host ?????,??server??host.?????rabbitmq??????????
    virtual-host: xuniji1